import { pgTable, uuid, text, timestamp, jsonb, pgEnum } from 'drizzle-orm/pg-core';
import { builderSessions } from './builder-sessions';

/**
 * Message Role Enum
 * 
 * USER      — message sent by the user
 * ASSISTANT — message generated by the AI (Gemini)
 * SYSTEM    — system-level messages (e.g., session started)
 */
export const messageRoleEnum = pgEnum('message_role', [
    'USER',
    'ASSISTANT',
    'SYSTEM',
]);

/**
 * Chat Messages Table Schema
 * 
 * Stores every message in a builder session's conversation.
 * This is what makes the chat "stateful" — we persist all messages
 * in the database and reconstruct context for each LLM call.
 * 
 * Why persist in DB instead of relying on LLM memory?
 * - LLMs have context limits
 * - Server restarts won't lose conversation
 * - We can selectively load relevant history
 * - Enables conversation review and debugging
 */
export const chatMessages = pgTable('chat_messages', {
    /** Unique message ID */
    id: uuid('id').defaultRandom().primaryKey(),

    /** The session this message belongs to */
    sessionId: uuid('session_id')
        .notNull()
        .references(() => builderSessions.id, { onDelete: 'cascade' }),

    /** Who sent this message: USER, ASSISTANT, or SYSTEM */
    role: messageRoleEnum('role').notNull(),

    /** The actual message content */
    content: text('content').notNull(),

    /** 
     * Optional metadata (JSONB) — flexible storage for extra info.
     * For assistant messages, this might include:
     * - completion score at that point
     * - missing fields at that point
     * - any flags or context
     */
    metadata: jsonb('metadata'),

    /** When this message was sent */
    createdAt: timestamp('created_at').defaultNow().notNull(),
});

/** TypeScript type for a chat message row */
export type ChatMessage = typeof chatMessages.$inferSelect;

/** TypeScript type for inserting a new chat message */
export type NewChatMessage = typeof chatMessages.$inferInsert;
